/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        System.out.println("Para criar um triangulo escreva o nome e seu tamanho (isso serve para o losango também) e para fazer um retangulo escreva o nome e base e altura: ");

       if(args.length == 2) {
            String nome = args[0];
            int tamanho = Integer.parseInt(args[1]);
            if(tamanho > 0) {
                if(nome == "triangulo"){
                    for(int i = 0; i <= tamanho; i++) {
                       System.out.print(" ".repeat(tamanho - i - 1));
                       System.out.println("*".repeat(i + 1)); //não entendo porque o espaço não deixa ele ficar invertido
                    }
                }
                if(nome == "losango"){
                      int meio = tamanho / 2; //preciso da distancia antes de chegar no meio para ter controle dos espaços
                      for (int i = 0; i < tamanho; i++) {
                          int dis = Math.abs(meio - i); //distancia antes do meio, percebi que quando chegava no meio as vezes ele dava número negativo e o java reclamava que não pode ter numero negativo então pensei em resolver isso jogando um módulo pra ele não ficar negativo e acabei resolvendo o problema sem perceber (imprimir a parte debaixo kakakakak)
                          int espaco = dis; //autoexplicativo
                          System.out.print(" ".repeat(espaco));
                          System.out.println("*".repeat(tamanho - 2 * dis).trim()); //descobri que o .trim tira espaços de strings achei no google teacher its ok
                      }
                }
            }
            System.out.println("Erro: valores para o tamanho do triângulo/losango são negativos");
            return;
        }
        else if(args.length == 3) {
            String nome = args[0];
            int base = Integer.parseInt(args[1]);
            int altura = Integer.parseInt(args[2]);

            if(base < 0 || altura < 0){
                System.out.println("Erro: valores atribuídos a bas/altura são negativos.");
                return;
            }
           //Primeiro printamos a parte de cima do retangulo
           System.out.println("*".repeat(base));

           //Agora está na hora de printar as colunas verticais ("e existe coluna horizontal?")
           int espaco = base - 2; //olhei pra imagem e achei esse padrão (tomara que dê certo)
           for(int i = 0; i < altura - 2; i++){
               System.out.print("*");
               System.out.print(" ".repeat(espaco));
               System.out.print("*");
               System.out.println();
           }

           //E por ultimo a parte debaixo do retangulo
           System.out.print("*".repeat(base));
           return;
        }
        else{
            System.out.println("Erro: você digitou mais argumentos/menos que o necessário (nome e tamanho para triangulo e losangulo, nome base e altura para o retangulo)");
            System.out.println("Try again, i believe in you!");
           return;
       }
    }
}
